### ISSUE TITLE
'nccl' not available for Windows

### ISSUE THREAD

**Issue by hanhern** [StuvX/SpotRust#1]
Hi - I would love to use this project but unfortunately I can't run it on my windows machine because 'nccl' is not supported. Do you know if I could use your weights but with a different inference .py file? Or do you know if I could remove 'nccl' from the inference .py file without affecting the performance? Thank you very much!

**Comment by StuvX** [comment]
Windows is not supported, however NCCL is an nvidea acceleration library, you should be able to modify the code to run without it. I would recommend using GPU acceleration and to install Windows Subsystem Linux for deep learning applications.

**Comment by jackthelad0312** [comment]
dist.init_process_group('gloo', rank=rank, world_size=world_size)       #nccl  -> gloo
